spring.datasource.url=jdbc:postgresql://localhost:5432/mydb
spring.datasource.username=dev
spring.datasource.password=dev26

project.name=notification-service
project.version=1.0.0
project.description=Notification Service for sending emails and SMS
project.author=Mukund
profiles.active=dev
spring.profiles.active=${profiles.active}
spring.jpa.hibernate.ddl-auto=update